version: '3.8'

services:
  student-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student-api-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-XX:+UseZGC -XX:+EnableDynamicAgentLoading -Xmx512m -Xms256m
    networks:
      - student-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a database service (PostgreSQL)
  # Uncomment if you want to add database support
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: student-db
  #   environment:
  #     POSTGRES_DB: studentdb
  #     POSTGRES_USER: student
  #     POSTGRES_PASSWORD: password123
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - student-network
  #   restart: unless-stopped

networks:
  student-network:
    driver: bridge

# volumes:
#   postgres_data: